
package com.example.demo.class5;

import com.example.demo.class5.BoxUserCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "BoxUser". Can be used for QueryBuilder and for referencing DB names.
 */
public final class BoxUser_ implements EntityInfo<BoxUser> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "BoxUser";

    public static final int __ENTITY_ID = 1;

    public static final Class<BoxUser> __ENTITY_CLASS = BoxUser.class;

    public static final String __DB_NAME = "BoxUser";

    public static final CursorFactory<BoxUser> __CURSOR_FACTORY = new Factory();

    @Internal
    static final BoxUserIdGetter __ID_GETTER = new BoxUserIdGetter();

    public final static BoxUser_ __INSTANCE = new BoxUser_();

    public final static io.objectbox.Property<BoxUser> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<BoxUser> userId =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, int.class, "userId");

    public final static io.objectbox.Property<BoxUser> userName =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "userName");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<BoxUser>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        userId,
        userName
    };

    public final static io.objectbox.Property<BoxUser> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<BoxUser> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<BoxUser>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<BoxUser> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<BoxUser> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<BoxUser> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class BoxUserIdGetter implements IdGetter<BoxUser> {
        @Override
        public long getId(BoxUser object) {
            return object.id;
        }
    }

}
