
package com.example.demo.class5;

import io.objectbox.BoxStore;
import io.objectbox.BoxStoreBuilder;
import io.objectbox.ModelBuilder;
import io.objectbox.ModelBuilder.EntityBuilder;
import io.objectbox.model.PropertyFlags;
import io.objectbox.model.PropertyType;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.
/**
 * Starting point for working with your ObjectBox. All boxes are set up for your objects here.
 * <p>
 * First steps (Android): get a builder using {@link #builder()}, call {@link BoxStoreBuilder#androidContext(Object)},
 * and {@link BoxStoreBuilder#build()} to get a {@link BoxStore} to work with.
 */
public class MyObjectBox {

    public static BoxStoreBuilder builder() {
        BoxStoreBuilder builder = new BoxStoreBuilder(getModel());
        builder.entity(BoxUser_.__INSTANCE);
        return builder;
    }

    private static byte[] getModel() {
        ModelBuilder modelBuilder = new ModelBuilder();
        modelBuilder.lastEntityId(1, 6672286885858678880L);
        modelBuilder.lastIndexId(0, 0L);
        modelBuilder.lastRelationId(0, 0L);

        buildEntityBoxUser(modelBuilder);

        return modelBuilder.build();
    }

    private static void buildEntityBoxUser(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("BoxUser");
        entityBuilder.id(1, 6672286885858678880L).lastPropertyId(3, 419810837274079158L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 7362486308284753115L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("userId", PropertyType.Int).id(2, 2414114165967514576L)
                .flags(PropertyFlags.NOT_NULL);
        entityBuilder.property("userName", PropertyType.String).id(3, 419810837274079158L);


        entityBuilder.entityDone();
    }


}
